# Generated by Django 5.2.5 on 2025-08-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prop_uri",
                    models.CharField(
                        choices=[
                            ("http://xmlns.com/foaf/0.1/homepage", "Homepage"),
                            ("http://purl.org/dc/terms/rightsHolder", "Rights Holder"),
                            ("http://purl.org/dc/terms/created", "Date Created"),
                        ],
                        help_text="e.g. foaf:homepage",
                        max_length=300,
                        verbose_name="URL of the property",
                    ),
                ),
                (
                    "prop_value",
                    models.CharField(
                        help_text="e.g. 'http://foo-bar' or a date 'YYYY-MM-DD'",
                        max_length=300,
                        verbose_name="Poperty value",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom property",
                "verbose_name_plural": "Custom properties",
                "ordering": ["id"],
            },
        ),
    ]
