# Generated by Django 5.2.5 on 2025-08-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0003_customproperty_prop_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='skosconceptscheme',
            name='custom_props',
            field=models.ManyToManyField(blank=True, null=True, to='vocabs.customproperty', verbose_name='Custom properties'),
        ),
        migrations.AlterField(
            model_name='customproperty',
            name='prop_lang',
            field=models.CharField(default='en', help_text="e.g. 'de', defaults to 'en'", max_length=3, verbose_name='Language'),
        ),
    ]
