# Generated by Django 5.2.5 on 2025-08-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0004_skosconceptscheme_custom_props_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skosconceptscheme',
            name='custom_props',
        ),
        migrations.AddField(
            model_name='skosconceptscheme',
            name='custom_prop',
            field=models.ManyToManyField(blank=True, to='vocabs.customproperty', verbose_name='Custom properties'),
        ),
    ]
