# Generated by Django 5.2.5 on 2025-08-22 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabs", "0005_remove_skosconceptscheme_custom_props_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skosconceptscheme",
            name="custom_prop",
        ),
        migrations.AddField(
            model_name="customproperty",
            name="concept_scheme",
            field=models.ForeignKey(
                help_text="Skos:ConceptScheme of this custom property ",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="has_custom_properties",
                to="vocabs.skosconceptscheme",
                verbose_name="skos:ConceptScheme",
            ),
            preserve_default=False,
        ),
    ]
