language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations --settings=vocabseditor.settings.dev
  - python manage.py migrate --settings=vocabseditor.settings.dev
  - python manage.py test --settings=vocabseditor.settings.dev