version: "3"
services:
  web:
    build: .
    environment:
      - POSTGRES_DB=vocabs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      - PROJECT_NAME=vocabseditor
      - SECRET_KEY=randomstring
      - DEBUG=True
      - DJANGO_SUPERUSER_USERNAME=user_name
      - DJANGO_SUPERUSER_PASSWORD=user_pw
      - VOCABS_DEFAULT_PEFIX=myvocabs
      - VOCABS_DEFAULT_PEFIX=de
      - REDMINE_ID=12345
      - MIGRATE=yes
    network_mode: host