name: Test and Publish

on: [push]

jobs:
  rancher:
     name: Deploy to rancher
     runs-on: ubuntu-latest
     steps:
     - name: Rancher Deploy Action
       uses: yantadeu/rancher-deploy-action@v0.0.3
       env:
          RANCHER_ACCESS_KEY: ${{ secrets.RANCHER_ACCESS_KEY }}
          RANCHER_SECRET_KEY: ${{ secrets.RANCHER_SECRET_KEY }}
          RANCHER_URL_API: ${{ secrets.RANCHER_URL_API }}
          SERVICE_NAME: 'vocabseditor:vocabsmanual'
          DOCKER_IMAGE: 'acdhch/vocabseditor'
          DOCKER_IMAGE_LATEST: ''
