name: Test

on:
  push:

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    env:
      SQLITE: True
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test